---
apiVersion: v1
kind: Namespace
metadata:
  name:  demo-policies

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: demo-policies
  namespace: demo-policies
spec:
  hard:
    pods: "14"
    secrets: "3"
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-policies
  labels:
    app: demo-policies
  namespace: demo-policies
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: demo-policies
  template:
    metadata:
      labels:
        app: demo-policies
    spec:
      containers:
      - name: demo-policies
        image: neotkm/pod-healthcheck:v0.03
        resources:
          requests:
            cpu: 0.1
            memory: 100Mi
          limits:
            cpu: 0.1
            memory: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-policies-2
  labels:
    app: demo-policies-2
  namespace: demo-policies
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: demo-policies-2
  template:
    metadata:
      labels:
        app: demo-policies-2
    spec:
      containers:
      - name: demo-policies-2
        image: neotkm/pod-healthcheck:v0.03
        resources:
          requests:
            cpu: 0.1
            memory: 100Mi
          limits:
            cpu: 0.1
            memory: 100Mi
