---
apiVersion: v1
kind: Namespace
metadata:
  name:  demo-pod-security-policy

---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: demo-pod-security-policy
  namespace: demo-pod-security-policy
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'

---
apiVersion: v1
kind: Pod
metadata:
  name:      privileged-pod
  namespace: demo-pod-security-policy
spec:
  containers:
    - name:  pause
      image: k8s.gcr.io/pause
      securityContext:
        privileged: true
