---
apiVersion: v1
kind: Namespace
metadata:
  name: daemonset-demo

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-demo
  labels:
    app: daemonset-demo
  namespace: daemonset-demo
spec:
  strategy:
    #type: RollingUpdate
    #type: Recreate
    #rollingUpdate:
      #maxSurge: 25%
      #maxUnavailable: 25%
  selector:
    matchLabels:
      app: daemonset-demo
  template:
    metadata:
      labels:
        app: daemonset-demo
    spec:
      containers:
      - name: daemonset-demo
        image: neotkm/pod-healthcheck:v0.03
        #imagePullPolicy: Always
        #imagePullPolicy: Never
        #imagePullPolicy: IfNotPresent

      #restartPolicy: Always

      #imagePullSecrets:
      #  - name: myregistrykey
