---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: %changeme%-app
  labels:
    app: %changeme%-app
  namespace: %changeme%-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    #type: Recreate
    #rollingUpdate:
      #maxSurge: 25%
      #maxUnavailable: 25%
  selector:
    matchLabels:
      app: %changeme%-app
  template:
    metadata:
      labels:
        app: %changeme%-app
    spec:
      containers:
      - name: %changeme%-app
        image: neotkm/pod-healthcheck:v0.05
        env:
          - name: PORT
            value: "2020"
          - name: MESSAGE
            value: "TEST MESSAGE"
        #imagePullPolicy: Always
        #imagePullPolicy: Never
        #imagePullPolicy: IfNotPresent

      #restartPolicy: Always

      #imagePullSecrets:
      #  - name: myregistrykey
