---
apiVersion: v1
kind: Namespace
metadata:
  name: pod-demo

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod-demo
  name: pod-demo
  namespace: pod-demo
spec:
  containers:
  - name: pod-demo
    image: neotkm/pod-healthcheck:v0.03
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', 'echo waiting for myservice; sleep 2;']
  - name: init-mydb
    image: busybox:1.28
    command: ['sh', '-c', 'echo waiting for mydb; sleep 2;']
#  restartPolicy: Never
#  restartPolicy: OnFailure
  restartPolicy: Always


