---
apiVersion: v1
kind: Namespace
metadata:
  name: pod-demo

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod-demo
  name: pod-demo
  namespace: pod-demo
spec:
  containers:
  - name: pod-demo
    image: neotkm/pod-healthcheck:v0.03
    #imagePullPolicy: Always
    #imagePullPolicy: Never
    imagePullPolicy: IfNotPresent

  #restartPolicy: Never
  #restartPolicy: OnFailure
  restartPolicy: Always

  #imagePullSecrets:
  #  - name: myregistrykey
