---
apiVersion: v1
kind: Namespace
metadata:
  name: replicaset-demo

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-demo
  labels:
    app: replicaset-demo
  namespace: replicaset-demo
spec:
  replicas: 6
  selector:
    matchLabels:
      app: replicaset-demo
  template:
    metadata:
      labels:
        app: replicaset-demo
    spec:
      containers:
      - name: replicaset-demo
        image: neotkm/pod-healthcheck:v0.03
        #imagePullPolicy: Always
        #imagePullPolicy: Never
        #imagePullPolicy: IfNotPresent

      #restartPolicy: Always

      #imagePullSecrets:
      #  - name: myregistrykey
